name: kh_driving_rule
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.0
  path_provider: ^2.1.5
  open_filex: ^4.4.0
  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/data/theory_data.json
    - assets/data/laws_data.json
    - assets/images/
    - assets/pdf/
    - assets/icons/
    - assets/data/



  fonts:
    - family: KohSantepheap
      fonts:
        - asset: assets/fonts/KohSantepheap-Regular.ttf
        - asset: assets/fonts/KohSantepheap-Bold.ttf
